services:
  - type: web
    name: cardio-prediction
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0